// Shared mixing configuration.
// IMPORTANT: changing these values invalidates the constants table generated by
// utils/emit-constants.mjs. After any change, re-run that script and commit
// both this file and the regenerated constants.ts together.

export const BASE_COLOR = "#2190bc";

// Asymmetric weights applied to the (sorted) (low, high) private pair plus the
// base color. The asymmetry breaks additive A+B collisions that limit
// equal-weight mixes.
export const W_BASE = 0.10;
export const W_LOW = 0.35;
export const W_HIGH = 0.55;
